// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/25/2025, 4:05:47 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/sao/Documents/freelance_website/static-template/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/freelance_website/static-template/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/freelance_website/static-template/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/freelance_website/static-template/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/freelance_website/static-template/plugins/**/*.{js,ts,mjs}","C:/Users/sao/Documents/freelance_website/static-template/composables/**/*.{js,ts,mjs}","C:/Users/sao/Documents/freelance_website/static-template/utils/**/*.{js,ts,mjs}","C:/Users/sao/Documents/freelance_website/static-template/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/freelance_website/static-template/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/freelance_website/static-template/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/freelance_website/static-template/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;