// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/25/2025, 5:21:55 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/sao/Documents/my-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/my-site/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/my-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/my-site/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/my-site/plugins/**/*.{js,ts,mjs}","C:/Users/sao/Documents/my-site/composables/**/*.{js,ts,mjs}","C:/Users/sao/Documents/my-site/utils/**/*.{js,ts,mjs}","C:/Users/sao/Documents/my-site/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/my-site/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/my-site/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sao/Documents/my-site/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["23"] = "C:/Users/sao/Documents/my-site/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;